### PR TITLE
chore: add rollup 3 support

### PR DESCRIPTION
**Pull request by perrin4869**
I've been using this plugin with rollup v3 for a while, didn't find any issues.
Updated the tests to pass under both v2 and v3.
Updated dev dependencies

### CODE REVIEW

**Comment by perrin4869** [comment]
@JRJurman just pinging

**Comment by JRJurman** [comment]
@perrin4869 thank you for the ping, I completely missed this! I can merge and publish this today!

**Review by JRJurman — APPROVED** [review]
These changes all look good to me, thank you for updating the tests as well!

**Comment by JRJurman** [comment]
This has been published under the 4.1.0 release 🎉

**Comment by perrin4869** [comment]
Thank you!

**Pull request merged**
